### ISSUE TITLE
 Many Radius authentication calls happening even after successful authentication in Httpd 2.4.37

### ISSUE THREAD

**Issue by JugeshHM** [simeonmiteff/mod_auth_xradius#2]
We are using Radius external authentication using Httpd 2.4.37 with mod_auth_xradius. There are numerous calls to Radius server even though it authentication is successful. Can you please tell us how to stop continuous Radius authentication calls.

**Comment by simeonmiteff** [comment]
Hi @JugeshHM - no idea why this is happening or how to fix it, sorry. I'm not the author of this module - I mirrored it from http://www.outoforder.cc/projects/httpd/mod_auth_xradius/ and fixed the code to make it build with Apache from 8 years ago.

The page linked above has some details about mailing lists. They look pretty dead but you could try asking there.

In general I wouldn't recommend RADIUS for web stuff, maybe look at replacing this with a module to authenticate against whatever backend the RADIUS server is using (LDAP or some RDBMS most likely).
